### ISSUE TITLE
redundant "Accept-Encoding" header

### ISSUE THREAD

**Issue by ariebovenberg** [ramonsaraiva/pubg-python#1]
In `RequestMixin`, I see you're adding the `Accept-Encoding: gzip` header. 
`requests` adds an `Accept-Encoding: gzip, deflate` header for you automatically, so there shouldn't be a need to do this manually.

See the docs [here](http://docs.python-requests.org/en/master/user/quickstart/#binary-response-content)

**Comment by ramonsaraiva** [comment]
True, nice catch! Will remove that :+1:
