### ISSUE TITLE
Issues with code in the read me

### ISSUE THREAD

**Issue by irr1449** [ramonsaraiva/pubg-python#11]
Under "Playing around with data" 

The line

players = api.players().filter(players_names['epickitten']) 

Should be player_names not players_names. 

players = api.players().filter(player_names['epickitten']) 

I would be more than happy to make fixes.  Can I upload my own fixes to the repo?

**Comment by ramonsaraiva** [comment]
Hell yeah!

Please do it - whatever you want to contribute.
Open a Pull Request and i'll merge it if the changes make sense.

**Comment by ramonsaraiva** [comment]
If you've never done that before, here are some pretty good guides from GitHub https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by dandyrilla** [comment]
I'm not sure, I think that you just omitted equal sign between `player_names` and `['epickitten']`. I understood that .filter() method accepts only string which exists FILTER_MAPPING.

```
## original
players = api.players().filter(player_names['epickitten'])

## suggested to fix
players = api.players().filter(player_names=['epickitten'])
```

**Comment by ramonsaraiva** [comment]
@dandyrilla I think there's still a typo in this section https://github.com/ramonsaraiva/pubg-python#playing-around-with-data - it says `players_names` and not `player_names`.

I'll give him a buffer to create a PR and fix that, if not i can fix it.

**Comment by dandyrilla** [comment]
@ramonsaraiva 
I'm very impressed by your quick response. Thank you for taking account into my suggestion. Yeah, let's wait for his PR.

**Comment by ramonsaraiva** [comment]
Fixed.
