### ISSUE TITLE
ReadMe Telemetry Issue

### ISSUE THREAD

**Issue by adodell** [ramonsaraiva/pubg-python#12]
The code as follows in the ReadMe under the Telemetry section does not work...

`match = api.matches().get('276f5bcb-a831-4e8c-a610-d2073692069e')
asset = match.assets[0]
telemetry = api.telemetry(asset.url)

Traceback (most recent call last):

  File "<ipython-input-20-78a60363572b>", line 3, in <module>
    telemetry = api.telemetry(asset.url)

AttributeError: 'PUBG' object has no attribute 'telemetry'`

I'm sure the telemetry info is there since I see code written for it in the package, but it looks like the PUBG object doesnt have a "telemetry" method to call.

I'm sure I'm not the only one who has had this problem, what is the simplest way to access Telemetry data?

**Comment by ramonsaraiva** [comment]
Are you sure you have the latest version? If not please upgrade to `0.2.2`
`pip install pubg_python==0.2.2`

**Comment by adodell** [comment]
Fixed! you're right, might be because I'm on Windows but my default pip install was 0.2.1
