### ISSUE TITLE
Usage of api.players().filter()

### ISSUE THREAD

**Issue by Haza** [ramonsaraiva/pubg-python#14]
Hi !

I'm testing around with your wrapper. 
Right now, I am trying to retrieve some user data.
Using api.players().get() I can get a response from the API, everything seems good.

Using  api.players().filter(), the query does not seems to be fired and I do not get any data from the API.

Here is my code 
```
api = PUBG('<key>', <shard>)
# accound ID and player name are mine :-)
player = api.players().get('account.d70754df232c42b2b63dc0525c99acfb')
players = api.players().filter(player_names=['Hazadess'])
```
And the debug output
![capture_36789f](https://user-images.githubusercontent.com/204144/38410717-a435c95e-3985-11e8-8da0-72919df08591.png)

Do I miss something ?
Thanks !

**Comment by Haza** [comment]
Ok, I found it !

`api.players().filter()` return a collection of players and then you can iterate over it. (for x in y, or players[0], ... )

It wasn't very obvious for me. Maybe we can improve the small example in the Readme (Retrieving a list of players filtering by names) ? 
What do you think ?

Thanks !

**Comment by ramonsaraiva** [comment]
Please do it! :-)
