### ISSUE TITLE
Support season data

### ISSUE THREAD

**Issue by ramonsaraiva** [ramonsaraiva/pubg-python#31]
Add support for recently added season data https://documentation.playbattlegrounds.com/en/players-endpoint.html

**Comment by ramonsaraiva** [comment]
Requested changes here https://github.com/ramonsaraiva/pubg-python/pull/42 but no response yet.

**Comment by JacquesJacob** [comment]
Ramon, could you please tell me which season is the recent that I can get my players status no matter the region? Because currently the region of the servers are random and cant be selected. 
Thank you for your support.

**Comment by ramonsaraiva** [comment]
Seasons are now supported from version 0.8.2 https://pypi.org/project/pubg-python/0.8.2/
For usage documentation, refer to: https://github.com/ramonsaraiva/pubg-python#seasons
