### ISSUE TITLE
How often do new updates get pushed to pip?

### ISSUE THREAD

**Issue by jackbrown1993** [ramonsaraiva/pubg-python#39]
Current PIP installation is old and broken, am I missing something?

**Comment by ramonsaraiva** [comment]
What is broken in the current one? I haven't pushed a new version for a while, they might have changed a major thing and the API is not versionized, so it might happen.

Show me what is breaking for you and your version and I'll fix it.

**Comment by jackbrown1993** [comment]
Pull request #37 isn’t included in PIP package which breaks some of the telemetry stuff. Sorry I am on mobile at the moment so limited on information.

**Comment by ramonsaraiva** [comment]
Merging and doing a new deploy.
