### ISSUE TITLE
Characters in "characters" list in "LogMatchStart" events have all attributes set to "None"

### ISSUE THREAD

**Issue by absolutelysimon** [ramonsaraiva/pubg-python#52]
Steps to reproduce:

Create a telemetry object, tele, then:
```
new_match_event = tele.events_from_type("LogMatchStart")[0]
print(f"Telemetry character: {new_match_event.characters[0].name}")
```

**Comment by ramonsaraiva** [comment]
I'm experiencing the same behaviour here @absolutelysimon - looking into this.

**Comment by ramonsaraiva** [comment]
The issue is when calling `deserialize` in `Character` or any other `Object`.

For lists, I was not returning a `TelemetryData` instance when retrieving it from a parent `TelemetryData`, so `deserialize` was failing cause it always expects a `TelemetryData` instance other than a `dict`.
