### ISSUE TITLE
Api did not return my account 

### ISSUE THREAD

**Issue by justxor** [ramonsaraiva/pubg-python#67]
i am trying to return information about my account 
```
from pubg_python import PUBG, Shard

api = PUBG(mykey, Shard.PC_RU)
print(api)
players = api.players().filter(player_names=['Serjlife'])
player = players[0]
print(player.id)
print(player.matches)
``` 
and got the following error :

`pubg_python.exceptions.NotFoundError: The specified resource was not found`

**Comment by ramonsaraiva** [comment]
Are you sure you're specifying the proper name? Have you played in the past few days?

**Comment by justxor** [comment]
@ramonsaraiva 100% correct and yes i played today also tried for my second account Alvasil , it did not work also 
[FNS_5543_550614470765_97286dfc896d41b1a31042ce6623e92d_ИП_04_35.zip](https://github.com/ramonsaraiva/pubg-python/files/3556833/FNS_5543_550614470765_97286dfc896d41b1a31042ce6623e92d_._04_35.zip)

**Comment by ramonsaraiva** [comment]
That doesn't seem to be PUBG, but PUBG Lite, right?

**Comment by justxor** [comment]
@ramonsaraiva  not sure i am playing it on my phone  , it has any difference for api using ?

**Comment by ramonsaraiva** [comment]
Yes, I don't think the API currently supports PUBG Lite/mobile. There is no Shard available for those, take a look at: https://documentation.pubg.com/en/making-requests.html#platforms-and-regions

**Comment by justxor** [comment]
so maybe there is another way to get information from game from lite version , by tournament id or somehow else ?

**Comment by justxor** [comment]
i also have no idea how to get game id without user info call

**Comment by ramonsaraiva** [comment]
You can get it by tournament id: https://github.com/ramonsaraiva/pubg-python#retrieving-a-single-tournament
Seasons will be added soon to the wrapper as well.

**Comment by justxor** [comment]
i meant without player since i cant get match information via api

**Comment by ramonsaraiva** [comment]
You don't need a player to use the tournaments endpoint, you can use `api.tournaments()` to get a list of the available tournaments and `api.tournaments().get('tournament-id')` to get information about a specific tournament.

Please take some time to read the official/wrapper docs before asking questions.

**Comment by glmn** [comment]
> @ramonsaraiva not sure i am playing it on my phone , it has any difference for api using ?

Probably you play in **PUBG Mobile**. This is different game and also has different owner - Tencent Games. There is no public API yet for this game.

**Comment by ramonsaraiva** [comment]
Did you mean @justxor?
