### ISSUE TITLE
Release workflow is being triggered twice somehow

### ISSUE THREAD

**Issue by ramonsaraiva** [ramonsaraiva/pubg-python#71]

**Comment by ramonsaraiva** [comment]
Need to understand how to make https://github.com/ramonsaraiva/pubg-python/blob/master/.github/workflows/release.yml `on: release` trigger works only for when releases get published... not drafts/updates/creations, etc...

**Comment by glmn** [comment]
There is a [solution](https://help.github.com/en/articles/events-that-trigger-workflows#example-triggering-workflows-when-a-pull_request-is-assigned)

**Comment by ramonsaraiva** [comment]
Do you think it's just a matter of adding
```
types: [published]
```
?

**Comment by ramonsaraiva** [comment]
Just saw your PR, nvm.

**Comment by ramonsaraiva** [comment]
Worked 👍
