### ISSUE TITLE
I had to install the enum package, should it be added to the dependencies?

### ISSUE THREAD

**Issue by irr1449** [ramonsaraiva/pubg-python#9]

**Comment by irr1449** [comment]
I was using Python 2.7, I see this only works with Python 3.  Might want to put that somewhere in the readme?

**Comment by ramonsaraiva** [comment]
Hey,

Python 2.x will not be supported in this package, you should really consider start using Python 3, unless you have a really huge codebase that can't be ported atm.

I added `enum34` to the setup for versions lte 3.4 here https://github.com/ramonsaraiva/pubg-python/pull/10

I'll add to the README the versions the library currently support, no worries.

**Comment by irr1449** [comment]
Thanks.  I made a 3.X env. and its working.  I'm going to close this issue.
