### ISSUE TITLE
player.matches throws Attribute error (AttributeError: 'Player' object has no attribute 'matches')

### ISSUE THREAD

**Issue by nikhilbalwani** [ramonsaraiva/pubg-python#93]
![Screenshot from 2019-10-02 21-02-54](https://user-images.githubusercontent.com/31470608/66058548-30325b00-e558-11e9-9312-822c316d010f.png)

Selecting matches gives an AttributeError.

**Comment by glmn** [comment]
Last game was played over 6 months ago for player BringMeChicken, that is why there is no matches.
PUBG stores matches only for 14 days.
![image](https://user-images.githubusercontent.com/1326151/66070826-b18aed00-e55a-11e9-880a-645bab4a6690.png)

**Comment by petercubic** [comment]
I'm having a very similar issue, but I have an account with matches...

I'm basically using the sample code from GitHub.

```
from pubg_python import PUBG, Shard

apiKey = "###"

api = PUBG(apiKey, Shard.XBOX_NA)

player = api.players().get('account.9cf0aa41fda542acadfcffe6ca91bfa8')

for match in player.matches:
    match_data = api.matches().get(match.id)
```


And I'm getting this error:

```
Traceback (most recent call last):
  File "d:\Personal\PUBG\python\package_test.py", line 9, in <module>
    for match in player.matches:
AttributeError: 'Player' object has no attribute 'matches'
```

Any suggestions on what going on?
