### ISSUE TITLE
How to store the telemetry data as a json file?

### ISSUE THREAD

**Issue by az7139** [ramonsaraiva/pubg-python#97]
![01](https://user-images.githubusercontent.com/33395197/72319388-030a5280-36da-11ea-8933-765d8cf20056.PNG)
![02](https://user-images.githubusercontent.com/33395197/72319400-0998ca00-36da-11ea-8082-15b0c7a1af80.PNG)
Where is the problem?

**Comment by glmn** [comment]
You did try to dump Telemetry object which is not a json. `asset.url` just download this raw json

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by az7139** [comment]
> 您确实尝试转储不是json的遥测对象。`asset.url`只需下载此原始json
> 
> 与[GitHawk](http://githawk.com)发送[](http://githawk.c

> 您确实尝试转储不是json的遥测对象。`asset.url`只需下载此原始json
> 
> 与[GitHawk](http://githawk.com)发送[](http://githawk.com)

Thank you,I got it
